### ISSUE TITLE
CFB Revamped v8 Road to Glory Rosters are all messed up

### ISSUE THREAD

**Issue by IvoEenink** [cfbrevamped/CFBR-Easy-Installer#142]
Hi, I downloaded CFBR v8 last week and installed it on my ps3.
Mod works perfectly fine, love all the updates to schools, uni, rosters!
So i started an Road to Glory,, only after winning high school championship and choosing LSU on signing day i noticed in the depth chart the whole roster is messed up. Like randomly scrambled; My RB is now my QB and can't throw for shit.. second QB is an 6'8 guy but is named Kayshon Boutte (who would be a WR), Terrance Marshall became an 5'9 CB. Not only my team has this problem but also other schools.. like i mentioned the whole roster is messed up in RTG. 
I've also checked out some other players who uploaded RTG video's on youtube, I don't know wich version of CFBR they are playing but i noticed they all have same weird depth chart problems when you start college career. (doesn't matter wich school or what position you play)

Is this a thing that could be / will be fixed in coming version?

**Comment by platypocalypse** [comment]
This is an issue with named rosters in the base game, not the mod. When you create a player in RTG it loads the players from the base game roster rather than the one that was active when you started the mode. For some reason this causes players' names to shift positions as well. So your QBs are LSU's QBs from 2013 with names from other positions. My guess is Mettenberger is the starter and your backup is Steven Rivers.

The workaround is to create a player in team management and instead do the "use existing player" option of RTG. If you wanted to mirror it as close as possible, you could play through the entire High School season, commit, copy down your attributes. Then quit, create an identical player in your roster, and use that player as an "existing" RTG player.

**Comment by igloo1** [comment]
v11 now updates the RTG rosters
